// <auto-generated />
using Knapsack;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Knapsack.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Knapsack.Details", b =>
                {
                    b.Property<int>("TaskId");

                    b.Property<string>("ExecutionTime")
                        .IsRequired();

                    b.Property<int>("MaxWorth");

                    b.HasKey("TaskId");

                    b.ToTable("details");
                });

            modelBuilder.Entity("Knapsack.ExecutionProcess", b =>
                {
                    b.Property<int>("TaskId");

                    b.Property<string>("AllItems")
                        .IsRequired();

                    b.Property<string>("BestCombination")
                        .IsRequired();

                    b.Property<int>("CheckedCombCount");

                    b.Property<int>("CurCombEnd");

                    b.Property<int>("CurCombSize");

                    b.Property<string>("CurrentItemsCombination")
                        .IsRequired();

                    b.Property<int>("CurrentMaxWorth");

                    b.HasKey("TaskId");

                    b.ToTable("execution_processes");
                });

            modelBuilder.Entity("Knapsack.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Weight");

                    b.Property<int>("Worth");

                    b.HasKey("ItemId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Knapsack.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<int>("PercentComplete");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("TaskId");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("Knapsack.TaskItem", b =>
                {
                    b.Property<int>("TaskId");

                    b.Property<int>("ItemId");

                    b.HasKey("TaskId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("taskItem");
                });

            modelBuilder.Entity("Knapsack.Details", b =>
                {
                    b.HasOne("Knapsack.Task", "Task")
                        .WithOne("Details")
                        .HasForeignKey("Knapsack.Details", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Knapsack.ExecutionProcess", b =>
                {
                    b.HasOne("Knapsack.Task", "Task")
                        .WithOne("ExecutionProcess")
                        .HasForeignKey("Knapsack.ExecutionProcess", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Knapsack.TaskItem", b =>
                {
                    b.HasOne("Knapsack.Item", "Item")
                        .WithMany("TaskItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Knapsack.Task", "Task")
                        .WithMany("TaskItems")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
